version: '3'

networks:
  nginx-php74-mysql8:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./NGINX/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mysql8-service
    networks:
      - nginx-php74-mysql8

  # php
  php74-service:
    build:
      context: .
      dockerfile: ./PHP/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    container_name: app-container
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9200:9200"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php74-mysql8
  
  composer:
    restart: 'no'
    image: composer:latest
    command: ["composer","install"]
    volumes:
      - ./app:/var/www/project
    working_dir: /var/www/project
    networks:
      - nginx-php74-mysql8
    depends_on:
      - php74-service 

  # mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8
    ports:
      - "4306:3306"
    volumes:
      - ./MYSQL:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   # restart: always always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - nginx-php74-mysql8

